#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2023.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Feb 10 12:15:04 CST 2026
# SW Build 4029153 on Fri Oct 13 20:13:54 MDT 2023
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim mult_tb_top_behav -key {Behavioral:sim_1:Functional:mult_tb_top} -tclbatch mult_tb_top.tcl -protoinst "protoinst_files/design_1.protoinst" -view /home/fabian/Documents/TEC/Maestria/IC_2026/fpga_design/proyecto_corto_1/vivado_project/zynq_proc_mult_design/mult_tb_top_behav.wcfg -log simulate.log -testplusarg UVM_TESTNAME=mult_basic_test -testplusarg UVM_VERBOSITY=UVM_LOW"
xsim mult_tb_top_behav -key {Behavioral:sim_1:Functional:mult_tb_top} -tclbatch mult_tb_top.tcl -protoinst "protoinst_files/design_1.protoinst" -view /home/fabian/Documents/TEC/Maestria/IC_2026/fpga_design/proyecto_corto_1/vivado_project/zynq_proc_mult_design/mult_tb_top_behav.wcfg -log simulate.log -testplusarg UVM_TESTNAME=mult_basic_test -testplusarg UVM_VERBOSITY=UVM_LOW

